name: GitHub Actions Build and Deploy Yzh2002's Blog
on: # push到main分支上触发工作流程，并将打包产物部署到gh-pages分支
  push: 
    branches: main 
    #详细语法见：https://docs.github.com/cn/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest #github actions运行的虚拟机环境（也可以使用自己的环境）
    steps:
    - name: Fix Pandoc
    - uses: docker://pandoc/core:2.9
      with:
        args: "--help" # gets appended to pandoc command


    - name: Checkout #？？不是很明白？？？？
      uses: actions/checkout@v3

    - name: Install dependency 
      # install dependencies of hexo
      run: | 
        npm install hexo
        npm install
      # with:
        # node-version: "16"

    - name: Build
      run: npx hexo generate

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: public
